# Generated by Django 3.1.3 on 2020-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_addrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='file',
            field=models.FileField(upload_to='MainApp/images'),
        ),
    ]
