# Generated by Django 3.1.3 on 2020-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201119_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindishes',
            name='level',
            field=models.CharField(default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='maindishes',
            name='steps',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='file',
            field=models.ImageField(upload_to='MainApp/static/MainApp/images'),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='img',
            field=models.ImageField(upload_to='MainApp/static/MainApp/images'),
        ),
    ]
