# Generated by Django 3.1.3 on 2020-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_maindishes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindishes',
            name='ingred',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
