# Generated by Django 3.1.3 on 2020-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_maindishes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindishes',
            name='likes',
            field=models.ManyToManyField(to='MainApp.Login'),
        ),
    ]
