# Generated by Django 3.1.3 on 2020-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_maindishes_lik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='phone',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
