# Generated by Django 3.1.3 on 2020-11-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_auto_20201125_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
