# Generated by Django 3.1.3 on 2020-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_remove_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
