# Generated by Django 3.1.3 on 2020-11-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_auto_20201126_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catimg',
        ),
    ]
