# Generated by Django 3.1.3 on 2020-11-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_auto_20201127_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindishes',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.category'),
        ),
    ]
