# Generated by Django 3.1.3 on 2020-11-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_maindishes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindishes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category'),
        ),
    ]
