# Generated by Django 3.1.3 on 2020-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_auto_20201128_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='issue',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='ingred',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='level',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='steps',
            field=models.TextField(default=''),
        ),
    ]
